Rewrite with Qubes API and improved features

diff --git a/bin/qubes-template-update b/bin/qubes-template-update
--- a/bin/qubes-template-update
+++ b/bin/qubes-template-update
@@ -24,19 +24,26 @@ set -o noglob
 
 # Lockfile path
 lock_file="/tmp/qubes-template-update.lck"
+# qrexec_agent could be either 'qrexec-client' or 'qvm-run'
+qrexec_agent="qvm-run"
+# Colors for qvm-run
+color_output=91
+color_stderr=37
 
 ### End configs
 
 declare syntax="\
 This tool is a package manager helper for Qubes OS templates. It could check for
 availability of updates, download updates without installation, perform updates;
-search, install or remove individual packages from one or more templates.
-It is currently compatible with templates using apt(8), dnf(8) emerge(1) and 
-pacman(8) as their primary package manager. Use it at your own risk!
+search, install or remove individual packages on one or more templates.
+It is currently compatible with templates using apt(8), dnf(8), emerge(1) or
+pacman(8) as their primary package manager. This tool could be run from dom0 or
+on management VMs with sufficient privileges. Use it at your own risk!
 
 usage: qubes-template-update [--verbose|--quiet] [--assume-yes|assume-no]
                              [--refresh] [--skip-broken] [--download-only]
-                             [--dry-run] [--shutdown ...] [qvm-run(1) options]
+                             [--dry-run] [--auto-start|--no-autostart]
+                             [--after-update shutdown|running|revert-state]
                              [--apt OPTIONS] [--dnf OPTIONS]
                              [--emerge OPTIONS] [--pacman OPTIONS] [--help]
                              TEMPLATE|--all COMMAND ...
@@ -49,28 +56,25 @@ options:
   -n, --assume-no           automatically answer no to all questions
   --refresh                 update list of available packages within template
   --skip-broken             resolve depsolve problems by skipping packages or
-                            ignoring conflicts. usually a terrible idea,
-                            unless used together with '--download-only' option
+                            ignoring conflicts. this is usually a terrible idea,
+                            ...unless used with '--download-only' option
   --download-only           download packages without installation.
   --all, '*'                perform operation on all templates
-  --dry-run                 do not execute the actual command(s) but print them
-                            This option ignores --quiet & prints update command
-  --shutdown [OPTIONS]      shutdown template after task is complete.
-                            following options will be passed to qvm-shutdown(1):
-                            --wait, --timeout TIMEOUT, --force-shutdown
-  --apt OPTIONS             Custom options for apt(8)
-  --dnf OPTIONS             Custom options for dnf(8)
-  --emerge OPTIONS          Custom options for emerge(1)
-  --pacman OPTIONS          Custom options for pacman(8)
-
-qvm-run(1) options:
-  The following options will be forwarded to qvm-run(1):
-  --autostart, --auto, --no-autostart, --no-auto, --gui, --no-gui, --nogui,
-  --colour-output COLOUR, --color-output COLOUR, 
-  --colour-stderr COLOUR, --color-stderr COLOUR,
-  --no-colour-output, --no-color-output, --no-colour-stderr, --no-color-stderr,
-  --filter-escape-chars, --no-filter-escape-chars, --no-shell
-  Refer to qvm-run(1) manual for more information 
+  --dry-run                 do not execute the actual command(s) but print them.
+                            this option ignores --quiet to print update command
+                            if the template is not running,  package manager is
+                            guessed based on template name
+  --autostart, --auto       option ignored, this is default
+  --no-autostart, --no-auto do not autostart template(s)
+  --after-update, --after   by default, template status will be reverted to the
+                            situation before update task (revert-state). this
+                            behavior could be changed to 'shutdown' or keep
+                            them 'running' after update.
+                            paused or transient templates will not be touched!
+  --apt OPTIONS             Additional custom options for apt(8)
+  --dnf OPTIONS             Additional custom options for dnf(8)
+  --emerge OPTIONS          Additional custom options for emerge(1)
+  --pacman OPTIONS          Additional custom options for pacman(8)
 
 TEMPLATE
    At least one template. Comma-separated list is OK. Space separated list of
@@ -83,7 +87,7 @@ subcommands:
    salt-update              Update template(s) via Salt interface (experimental)
    update                   Download and/or Install updates for the template(s)
                             This is obsolete and highly discouraged.
-                            Unless used with --download-only option
+                            ...unless used with --download-only option
    install <PACKAGE> ...    Install package(s) on the template(s) 
    remove <PACKAGE> ...     Remove the specified package(s) from template(s)
    search <keywords>        Search for packages
@@ -101,23 +105,22 @@ declare SKIPBROKEN=false
 declare DOWNLOADONLY=false
 declare ALLTEMPLATES=false
 declare DRYRUN=false
-declare SHUTDOWN=false
+declare AUTOSTART=true
+declare AFTERUPDATE='revert-state'
 declare SUBCOMMAND=""
 
 declare -a template_patterns=()
 declare -a cmd_apt=(apt-get)
 declare -a cmd_dnf=(dnf)
-declare -a cmd_emerge=(emerge --color n)
+declare -a cmd_emerge=(emerge)
 declare -a cmd_pacman=(pacman)
-declare -a cmd_qvm_run=(qvm-run --user root --pass-io)
-declare -a cmd_qvm_shutdown=(qvm-shutdown)
-declare -a cmd_qubesctl=(qubesctl)
 
 declare SELF=${0##*/}
+declare HOSTNAME=$(hostname)
 
 # Synopsis: print_usage [EXIT_CODE]
 print_usage() {
-	! $QUIET && echo "${syntax}"
+	message "${syntax}"
 	[ ! -z ${1} ] && exit ${1}
 }
 
@@ -128,8 +131,8 @@ message() {
 
 # Synopsis: abort EXIT_CODE MESSAGE
 abort() {
-	message "error: ${2}"
-	message "Please see --help for more information."
+	message "error: ${2}" 1>&2
+	message "Please see --help for more information." 1>&2
 	exit ${1}
 }
 
@@ -139,13 +142,7 @@ parse_cmd_parameters() {
 		--longoptions verbose,quiet,help,assume-yes,assume-no \
 		--longoptions refresh,skip-broken,download-only,all,dry-run \
 		--longoptions autostart,auto,no-autostart,no-auto \
-		--longoptions gui,no-gui,nogui,no-shell \
-		--longoptions no-colour-output,no-color-output \
-		--longoptions no-colour-stderr,no-color-stderr \
-		--longoptions filter-escape-chars,no-filter-escape-chars \
-		--longoptions colour-output:,color-output: \
-		--longoptions colour-stderr:,color-stderr: \
-		--longoptions shutdown,wait,timeout:,force-shutdown \
+		--longoptions after-update:,after: \
 		--longoptions apt:,dnf:,emerge:,pacman: -- "${@}")
 
 	[[ ${?} -ne 0 ]] && abort 22 "Invalid option!"
@@ -155,7 +152,7 @@ parse_cmd_parameters() {
 
 	while true
 	do
-		case $1 in
+		case ${1} in
 			-v|--verbose) VERBOSE=true;;
 			-q|--quiet) QUIET=true;;
 			-h|--help) print_usage 0;;
@@ -166,19 +163,12 @@ parse_cmd_parameters() {
 			--download-only) DOWNLOADONLY=true;;
 			--all) ALLTEMPLATES=true;;
 			--dry-run) DRYRUN=true;;
-			--autostart|--auto|--no-autostart|--no-auto|\
-			--gui|--no-gui|--nogui|--no-shell|\
-			--no-colour-output|--no-color-output|\
-			--no-colour-stderr|--no-color-stderr|\
-			--filter-escape-chars|--no-filter-escape-chars)
-				cmd_qvm_run+=(${1});;
-			--colour-output|--color-output|\
-			--colour-stderr|--color-stderr)
-				cmd_qvm_run+=("${1}=${2}"); shift;;
-			--shutdown) SHUTDOWN=true;;
-			--wait) cmd_qvm_shutdown+=(--wait);;
-			--timeout) cmd__qvm_shutdown+=(${2}); shift;;
-			--force-shutdown) cmd_qvm_shutdown+=(--force);;
+			--autostart|--auto)
+				AUTOSTART=true;;
+			--no-autostart|--no-auto)
+				AUTOSTART=false;;
+			--after-update|--after)
+				AFTERUPDATE="${2}"; shift;;
 			--apt) cmd_apt+=(${2}); shift;;
 			--dnf) cmd_dnf+=(${2}); shift;;
 			--emerge) cmd_emerge+=(${2}); shift;;
@@ -189,14 +179,12 @@ parse_cmd_parameters() {
 		shift	
 	done
 
-	if $QUIET && $VERBOSE
-	then
+	if $QUIET && $VERBOSE; then
 		QUIET=false
 		abort 22 "Could not be Quiet and Verbose at the same time!"
 	fi
 
-	if $ASSUMEYES && $ASSUMENO
-	then
+	if $ASSUMEYES && $ASSUMENO; then
 		QUIET=false
 		abort 22 "Could not assume YES and NO at the same time!"
 	fi
@@ -208,6 +196,11 @@ parse_cmd_parameters() {
 		shift
 	fi
 
+	if ! [[ ${AFTERUPDATE} =~ ^(shutdown|running|revert-state)$ ]]; then
+		QUIET=false
+		abort 22 "Invalid option: ${AFTERUPDATE} for --after-update!"
+	fi
+
 	[[ $# -lt 1 ]] && abort 2 "Subcommand missing!"
 	synthesize_template_cmds "${@}"
 }
@@ -215,8 +208,6 @@ parse_cmd_parameters() {
 # Synopsys synthesize_template_cmds COMMAND
 synthesize_template_cmds() {
 	if ${QUIET}; then
-		cmd_qvm_run+=(--quiet)
-		cmd_qvm_shutdown+=(--quiet)
 		cmd_apt+=(-qqq)
 		cmd_dnf+=(--quiet)
 		cmd_emerge+=(--quiet)
@@ -224,12 +215,9 @@ synthesize_template_cmds() {
 	fi
 
 	if ${VERBOSE}; then
-		cmd_qvm_run+=(--verbose)
-		cmd_qvm_shutdown+=(--verbose)
 		cmd_dnf+=(--verbose)
 		cmd_emerge+=(--verbose)
 		cmd_pacman+=(--verbose)
-		cmd_qubesctl+=(--show-output)
 	fi
 
 	SUBCOMMAND="$1"
@@ -239,7 +227,7 @@ synthesize_template_cmds() {
 			# Check-only does not need more arguments
 			[[ $# -gt 1 ]] && abort 7 "Invalid argument: ${2}"
 			# Note: Special case! No need to handle per distro
-			# 'upgrades-status-notify' does the job for this task
+			# Qubes OS 'upgrades-status-notify' does a nice job.
 			cmd_all=("/usr/lib/qubes/upgrades-status-notify")
 			cmd_apt=("${cmd_all}")
 			cmd_dnf=("${cmd_all}")
@@ -257,9 +245,8 @@ synthesize_template_cmds() {
 			[[ $# -gt 1 ]] && abort 7 "Invalid argument: ${2}"
 			cmd_apt+=(full-upgrade)
 			cmd_dnf+=(upgrade)
-			${DOWNLOADONLY} && cmd_emerge+=(--fetchonly)
 			cmd_emerge+=(--update --deep --newuse --changed-use \
-				@world)
+				\@world)
 			cmd_pacman+=(--sync --sysupgrade)
 			;;
 		install)
@@ -268,7 +255,6 @@ synthesize_template_cmds() {
 			shift
 			cmd_apt+=(install "${@}")
 			cmd_dnf+=(install "${@}")
-			${DOWNLOADONLY} && cmd_emerge+=(--fetchonly)
 			cmd_emerge+=("--update ${@}")
 			cmd_pacman+=(--sync --needed "${@}")
 			;;
@@ -278,11 +264,10 @@ synthesize_template_cmds() {
 			shift
 			cmd_apt+=(remove "${@}")
 			cmd_dnf+=(remove "${@}")
-			cmd_emerge+=("--depclean ${@}")
+			cmd_emerge+=(--depclean "${@}")
 			cmd_pacman+=(--remove "${@}")
 			;;
 		search)
-			# We need keywords to search for
 			# We need a list of one or more packages to search for
 			[[ $# -lt 2 ]] && abort 7 "Arguments missing!"
 			shift
@@ -309,11 +294,12 @@ synthesize_template_cmds() {
 		# Special refresh case for apt(9) should be prepended to cmd
 		if ${QUIET}; then
 			cmd_apt=("apt-get -qqq update;" "${cmd_apt[@]}")
+			cmd_emerge=("emerge --sync --quiet;" "${cmd_emerge[@]}")
 		else
 			cmd_apt=("apt-get update;" "${cmd_apt[@]}")
+			cmd_emerge=("emerge --sync;" "${cmd_emerge[@]}")
 		fi
 		cmd_dnf+=(--refresh)
-		cmd_emerge=("emaint --auto sync;" "${cmd_emerge[@]}")
 		cmd_pacman+=(--refresh)
 	fi
 
@@ -339,41 +325,124 @@ synthesize_template_cmds() {
 	if ${DOWNLOADONLY}; then
 		cmd_apt+=(--download-only)
 		cmd_dnf+=(--downloadonly --nobest)
+		cmd_emerge+=(--fetchonly)
 		cmd_pacman+=(--downloadonly)
 	fi
-
-	${DRYRUN} && cmd_qvm_shutdown+=(--dry-run)
 }
 
-# Synopsis: update_template TEMPLATE
-update_template() {
+# Synopsis: qubesd_admin_api CALL DEST [ARGUMENTS]
+qubesd_admin_api() {
+	local -a returned_message
+	local -i message_type
+	readarray -t returned_message < <(\
+		qubesd-query --empty --null ${HOSTNAME} ${@} |\
+		tr '\0' '\n')
+	message_type=${returned_message[0]}
+	unset returned_message[0]
+	printf '%s\n' "${returned_message[@]}"
+	return ${message_type}
+}
+
+# Synopsis: power_state VM
+power_state() {
+	local api_response
+	local -a fields
+	api_response=($(qubesd_admin_api admin.vm.CurrentState $1))
+	printf "${api_response[3]##*=}"
+}
+
+# Synopsis: qrexec VM USER COMMAND...
+qrexec() {
+	local domain=${1}
+	local user=${2}
+	shift; shift
+	if $DRYRUN; then
+		local tmp=$QUIET
+		QUIET=false
+		message "Dry-running as ${user} on ${domain}: ${@}"
+		QUIET=$tmp
+		return
+	elif $VERBOSE; then
+		message "Running as ${user} on ${domain}: ${@}"
+	fi
+	if [ ${qrexec_agent} = "qrexec-client" ]; then
+		qrexec-client -tT -d ${domain} ${user}:"${@}"
+		return ${?}
+	elif [ ${qrexec_agent} = "qvm-run" ]; then
+		qvm-run --user=${user} --no-auto --no-gui --pass-io\
+			--color-output=${color_output} \
+			--color-stderr=${color_stderr} \
+			${domain} -- "${@}"
+		return ${?}
+	else
+		abort 22 "Invalid qrexec agent: ${qrexec_agent}"
+	fi
+}
+
+# Synopsis: detect_distro TEMPLATE
+detect_distro() {
 	local template="${1}"
-	local cmd_update
 	local -l ID
-	message "Working on ${template} template."
-	# Note: Qubes OS 4.2 templates provide /etc/os-release
+	# Qubes OS 4.2 templates provide /etc/os-release
 	# This was tested in February 2024
-	ID=$(${cmd_qvm_run[@]} ${template} -- "cat /etc/os-release" | \
-		awk -F= '/^ID=/ {print $2}')
+	ID=$(qrexec-client -d ${template} user:"cat /etc/os-release" | \
+		awk -F= '/^ID=/ {gsub(/"/, ""); print $2}')
+	printf "${ID}"
+}
+
+# Synopsis: update_template TEMPLATE STATE_BEFORE_UPDATE
+update_template() {
+	local template="${1}" state="${2,,}"
+	local cmd_update
+	local -l current_state ID
+
+	if ! [[ ${state} =~ ^(running|halted)$ ]]; then
+		message "Only running or halted templates could be updated!"
+		message "Ignoring ${template} which is currently ${state}."
+		return
+	fi
+
+	message "Working on ${template} template"
+
+	if [ $AUTOSTART = true ] && [ "${state}" = "halted" ] && \
+		[ $DRYRUN = false ];
+	then
+		$VERBOSE && message "Starting ${template} template."
+		qubesd_admin_api admin.vm.Start ${template} >/dev/null
+		[[ ${?} -ne 0 ]] && \
+			abort 42 "Qubes API call to start ${template}  failed!"
+	fi
+
+	current_state=$(power_state ${template})
+
+	if [  $current_state = "running" ]; then
+		ID=$(detect_distro "${template}")
+	else
+		ID="${template}"
+	fi
+
 	case "${ID}" in
 		*alpine*)
 			message "Alpine update is not yet implemented";;
 		*arch*|*manjaro*)
 			cmd_update="${cmd_pacman[@]}";;
-		*debian*|*kali*|*mint*|pop|*buntu*)
+		*debian*|*kali*|*mint*|pop|*buntu*|*whonix*)
 			cmd_update="${cmd_apt[@]}";;
 		*fedora*|*centos*|*rocky*)
 			cmd_update="${cmd_dnf[@]}";;
 		*gentoo*)
 			# Since emerge does not detect qvm-run -p as valid tty,
 			# Sadly it does not honor --ask option.
-			if ${ASSUMEYES} || \
+			if ${ASSUMEYES} || ${DOWNLOADONLY} ||\
 			[[ ${SUBCOMMAND} =~ ^(check-only|search|custom)$ ]];
 			then
 				cmd_update="${cmd_emerge[@]}"
 			else
-				message "Gentoo deserve user intervention"
-				message "add --assume-yes to override safety!"
+				message "Gentoo deserves user intervention." \
+					"Add --download-only to download" \
+					"without installation or add" \
+					"--assume-yes to override safety!"
+				unset cmd_update
 			fi;;
 		*nixos*)
 			message "NixOS update is not yet implemented";;
@@ -386,56 +455,73 @@ update_template() {
 		*)
 			message "Release: ${release} unknown! Skipping";;
 	esac
-	if ! ${DRYRUN}; then
-		if [ ! -z "$cmd_update" ]; then
-			"${cmd_qvm_run[@]}" ${template} -- "${cmd_update}"
-		fi
-	else
-		tmp=${QUIET}
-		QUIET=false
-		message "Dry-run:" \
-			"${cmd_qvm_run[@]}" ${template} -- "${cmd_update}"
-		QUIET=${tmp}
+
+	[ -z "${cmd_update}" ] && return
+
+	qrexec ${template} root "${cmd_update}"
+
+	if [ $DRYRUN = false ] && \
+		{ [ $AFTERUPDATE = "shutdown" ] || \
+		{ [ $AFTERUPDATE = "revert-state" ] && \
+			[ "${state}" = "halted" ]; }; };
+	then
+		$VERBOSE && message "Powering-off ${template} template."
+		qubesd_admin_api admin.vm.Shutdown ${template} >/dev/null
+		[[ ${?} -ne 0 ]] && \
+			abort 42 "Qubes API call to stop ${template}  failed!"
 	fi
-	${SHUTDOWN} && "${cmd_qvm_shutdown[@]}" ${template}
+	return
 }
 
 # Synopsis: update_templates TEMPLATE_PATTERNS
 update_templates() {
-	# We could check 'qvm-prefs $vm_name updateable' property to find
-	# updateable VMs. To include Standalone VMs. For future considration
-	local -a patterns=(${@}) templates=()
-	local all_vms=$(qvm-ls --raw-data --fields NAME,FLAGS)
-	local vm vm_name vm_fags template_qrexec template
-	local -l vm_type template_os
-	# Iterating through all Qubes VMs, add templates to templates variable 
-	for vm in $all_vms; do
-		vm_name=${vm%\|*}
-		vm_flags=${vm##*\|}
-		vm_type=${vm_flags:0:1}
-		[ ! ${vm_type} = "t" ] && continue
+	local -a patterns=(${@}) all_vms=() templates=()
+	local -A vm_class=() vm_state=()
+	local api_result records record vm template
+	api_result=$(qubesd_admin_api admin.vm.List dom0)
+	[[ ${?} -ne 0 ]] && abort 42 "Qubes API call to read VM List failed!"
+	readarray -t records <<< "${api_result}"
+	for record in "${records[@]}"; do
+		local fields
+		fields=($record)
+		all_vms+=(${fields[0]})
+		vm_class[${fields[0]}]=${fields[1]##*=}
+		vm_state[${fields[0]}]=${fields[2]##*=}
+	done
+	# Iterating through all Qubes VMs, if it is a template and matches the
+	# - provided pattern, add it to templates array
+	for vm in ${all_vms[@]}; do
+		[ ! ${vm_class[${vm}],,} == "templatevm" ] && continue
 		for pattern in ${patterns[@]}; do
-			if [[ ${vm_name} == ${pattern} ]]; then
-				templates+=(${vm_name})
+			if [[ ${vm} == ${pattern} ]]; then
+				templates+=(${vm})
 			fi
 		done
 	done
 	for template in ${templates[@]}; do 
-		template_os=$(qvm-features --quiet ${template} os)
-		if [[ ! ${template_os} = "linux" ]]; then
+		template_os=$(qubesd_admin_api \
+			admin.vm.feature.Get ${template} os)
+		if [[ ! $? == 0 ]]; then
+			message "Could not determin OS for ${template} via "\
+				"Qubes API! Ignoring."
+			continue
+		fi
+		if [[ ! ${template_os,,} == "linux" ]]; then
 			message "${template} is not Linux based. Ignoring."
 			# Windows updates could be implemented via powershell
 			# and 'wuauclt.exe /updatenow'.
-			# Only if we had a workign qrexec. Work in progress...
+			# Only if we had a working qrexec. Work in progress...
 			continue
 		fi
-		template_qrexec=$(qvm-features --quiet ${template} qrexec)
-		if [[ ! ${template_qrexec} = "1" ]]; then
-			message "${template} does not support qrexec. Ignoring."
+		template_qrexec=$(qubesd_admin_api \
+			admin.vm.feature.Get ${template} qrexec)
+		if [[ ! $? == 0 ]] || [[ ! ${template_qrexec} = "1" ]]; then
+			message "${template} does not support qrexec or " \
+			       "qrexec status unknown. Ignoring."
 			continue
 		fi
 		# We have a matching and supported template!
-		update_template ${template}
+		update_template ${template} ${vm_state[${template}]}
 	done
 }
 
